#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 <<-EOSQL1
	CREATE COLLATION "nb_NO.utf8" (LOCALE="nb_NO.UTF-8");
	CREATE DATABASE "${DB_DATABASE}";
	CREATE USER "${DB_USERNAME}" WITH ENCRYPTED PASSWORD '${DB_PASSWORD}';
	GRANT ALL PRIVILEGES ON DATABASE "${DB_DATABASE}" TO "${DB_USERNAME}";
EOSQL1
