version: '3'

services:

  db:
    build:
      context: ./docker/postgres
    volumes:
      - db_storage:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ub-baser-dev
      - POSTGRES_PASSWORD=ub-baser-dev
      - POSTGRES_INITDB_ARGS=--no-locale --encoding=UTF8

  app:
    build:
      context: .
    environment:
      - APP_ENV=dev
      - APP_DEBUG=true
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ub-baser-dev
      - POSTGRES_USER=ub-baser-dev
      - POSTGRES_PASSWORD=ub-baser-dev
      - APP_KEY=DoesNotNeedToBeRandomInDevEnviro
      - SAUCE_USERNAME
      - SAUCE_ACCESS_KEY
      - TEST_BASE_URL=http://localhost:8080
    ports:
      - 8080:80
    volumes:
      - .:/app/:ro
      # Writable directories
      - app_storage:/app/storage
      - app_bootstrap_cache:/app/bootstrap/cache
    depends_on:
      - db

volumes:
  app_storage:
  app_bootstrap_cache:
  db_storage:
