<?php

namespace App\Litteraturkritikk;

use Illuminate\Support\Arr;

class Publications {

    static protected $newspapers = [
        'Aftenposten',
        'VG',
        'Tidens Tegn',
        'Social-Demokraten',
        'Gula Tidend',
        'Den 17de Mai',
        'Morgenposten',
        'Nationen',
        'Fedraheimen',
        'Dagsposten',
        'Bergensposten',
        'Christiania-Posten',
        'Dagen',
        'Norske Intelligenssedler',
        'Nidaros',
        'Den Constitutionelle',
        'Arbeidet',
        'Breidablik',
        'Christiania Intelligentssedler',
        'Fædrelandet',
        'Oplandenes Avis',
        'Morgenavisen',
        'Adresseavisen',
        'Haugesunds Avis',
        'Stavanger Avis',
        'Kristiansands Stiftsavis',
        'Trondhjems Adresseavis',
        'Aalesunds Avis',
        'Arbeideravisen',
        'Middagsavisen',
        'Lærerstandens Avis',
        'Throndhjems Stiftsavis',
        'Oslo Aftenavis',
        'Kristiania Dagsavis',
        'Vesteraalens Avis',
        'Folkets Avis',
        'Arbeider-Avisa',
        'Dagsavisen',
        'Vaalebro Avis',
        'Sogns Avis',
        'Hordalands Avis',
        'Fylkesavisen',
        'Arbeideravisa',
        'Hortens Avis',
        'Sunnmøre Arbeideravis',
        'Trønder-avisa',
        'Arbeider-Avisen',
        'Christiansands Stiftsavis',
        'Fredrikshalds Avis',
        'Moss Avis',
        'Sandnes og Jærens Avis',
        'Firda og Sygnafylkets avis',
        'Ørsta Avis',
        'Skotfos Avis',
        'Aura Avis',
        'Vestlandets Avis',
        'Avisen',
        'Tvedestrand og omegns avis',
        'Helgelands Avis',
        'Utstillingsavisen',
        'Drammens Dagsavis',
        'Fredriksstads Avis',
        'Bergens Tidende',
        'Drammens Tidende',
        'Stavanger Amtstidende og Adresseavis',
        'Lister og Mandals Amtstidende og Adresseavis',
        'Norges Handels- og Sjøfartstidende',
        'Hamar Stiftstidende',
        'Ny Illustreret Tidende',
        'Luthersk Kirketidende',
        'Smaalenenes Amtstidende',
        'Norsk Skoletidende',
        'Illustreret Tidende',
        'Bergens Annonce-Tidende',
        'Bergens Stiftstidende',
        'Den norske Rigstidende',
        'Nyeste skilderie af Christiania og Stockholm. En politisk, literair og commersiel Tidende',
        'Nationaltidende',
        'Jarlsberg og Larviks Amtstidende',
        'Den Vestlandske Tidende',
        'Drammens tidende',
        'Folketidende',
        'Østlandsk Tidende',
        'Nordenfjeldsk Tidende',
        'Christiansands Tidende',
        'Den Norske Rigstidende',
        'Berlingske Tidende',
        'Sogns Tidende',
        'Tromsø Stiftstidende',
        'Dansk Litteratur-Tidende',
        'Nordisk Literatur-Tidende',
        'Hedemarkens Amtstidende',
        'Harstad Tidende',
        'Grimstad Adressetidende',
        'Ofotens Tidende',
        'Dalernes Tidende',
        'Bodø Tidende',
        'Norsk Kirketidende',
        'Departements-Tidende',
        'Nordre Trondhjems Amtstidende',
        'Jarlsberg og Laurviks Amtstidende',
        'Søndmøre Folketidende',
        'Norsk Boghandler-Tidende',
        'Ungdoms-Tidende',
        'Luren og Buskeruds Amtstidende',
        'Romsdals Amtstidende',
        'Søndre Trondhjems Amtstidende',
        'Literaturtidende',
        'Bratsberg Amtstidende',
        'Almueskole-Tidende',
        'Oplandske Tidende',
        'Fredriksstads Tidende',
        'Rigsdagstidende',
        'Fredriksstad og omegns tidende',
        'Trondhjems Amtstidende',
        'Buskeruds Amtstidende',
        'Nordisk Boghandler Tidende',
        'Ny Luthersk Kirketidende',
        'Sandefjords Tidende',
        'Helgelands Tidende',
        'Aalesunds Handels og Sjøfartstidende',
        'Aalborg Amtstidende',
        'Dansk Kirketidende',
        'Glomdalens Tidende',
        'Nedenes Amtstidende',
        'Glommendalens Annonce-Tidende',
        'Luthersk kirketidende',
        'Evangelisk luthersk Kirketidende. Organ for "Synoden for den norsk-evangelisk-lutherske Kirke i Amerika"',
        'Tidens Tegn. Literaturtidende',
        'Norsk Retstidende',
        'Kristians Amtstidende',
        'Tromsø-Tidende',
        'Østlandske Tidende',
        'Dagbladet',
        'Morgenbladet',
        'Arbeiderbladet',
        'Aftenbladet',
        'Stavanger Aftenblad',
        'Bergens Aftenblad',
        'Drammens Tidende og Buskerud Blad',
        'Illustreret Nyhedsblad',
        'Ørebladet',
        'Bergens Arbeiderblad',
        'Haugesunds Dagblad',
        'Folkebladet',
        'Drammens Blad',
        'Norsk Folkeblad',
        'Tønsbergs Blad',
        'Skolebladet',
        'Rjukan Dagblad',
        'Nationalbladet',
        'Høgskulebladet',
        'Nær og fjern. Et Ugeblad',
        'Det Norske Nationalblad',
        'Bergenske Blade',
        'Landsbladet',
        'Kongsberg Dagblad',
        'Telemark Arbeiderblad',
        'Kongsvinger Arbeiderblad',
        'Porsgrunds Dagblad',
        'Adressebladet',
        'Fredrikstad Dagblad',
        'Gudbrandsdalens Blad',
        'Sandefjords Blad',
        'Samfundsbladet',
        'Godtemplarbladet',
        'Norsk Høgskuleblad',
        'Fredrikstad Blad',
        'Fjordabladet',
        'Østfold Dagblad',
        'Søndre Bergenhus Folkeblad',
        'Ringerikes Blad',
        'Christianias Aftenblad',
        'Rjukan Arbeiderblad',
        'Vestfold Arbeiderblad',
        'Riksmaals-bladet',
        'Eidsvold Blad',
        'Nasjonalbladet',
        'Aalesunds Blad',
        'Sarpsborg Arbeiderblad',
        'Aftonbladet',
        'Vossebladet',
        'Norges Kommunistblad',
        'Nordfjord Folkeblad',
        'Drammens Dagblad',
        'Bondebladet',
        'Gjøviks Blad',
        'Radiobladet',
        'Fjordenes Blad',
        'Kragerø Blad',
        'Østlandets Blad',
        'Hamar Arbeiderblad',
        'Throndhjems Aftenblad',
        'Christiania Dagblad',
        'Lørdags-Aftenblad for Arbeidsklassen',
        'Haldens Arbeiderblad',
        'Daggry. Socialdemokratisk maanedsblad',
        'Telemark Dagblad',
        'i mai og juni',
        'Stavanger Morgenblad',
        'Norsk Skuleblad',
        'Nynorsk Vekeblad',
        'Møre Dagblad',
        'Firda Folkeblad',
        'Trondhjems Folkeblad',
        'Horten Arbeiderblad',
        'Nordlands Folkeblad',
        'Østerdal Folkeblad',
        'Norsk Kirkeblad',
        'Illustreret Familieblad',
        'Folkets Dagblad',
        'Porsgrunds Blad',
        'Kongsberg blad. Liberalt blad for Kongsberg og omegn',
        'Venstrebladet',
        'Norsk Barneblad',
        'Tiraljøren. Blade oplæste og angrebne i Studentersamfundet',
        'Hordalands Folkeblad',
        'Søndagsbladet',
        'Laurviks Blad',
        'Trønderske Blade',
        'Totens Blad',
        'Helgelands Blad',
        'Anton Martin Schweigaard. Født den 11.april 1808, død den 1. februar 1870. Mindeblade',
        'Arbeiderbladets Ukemagasin. Lørdagskvelden',
        'Bygdebladet',
        'Aftenposten (Christiania Adresseblad)',
        'Breviks Dagblad',
        'Østfold Arbeiderblad',
        'Ekstrabladet',
        'Fra de talendes lejr. Flyveblad til fru Camilla Collett',
        'Kristelig Ukeblad',
        'Norskt Høgskuleblad',
        'Molde Annonceblad',
        'Kirkeligt Folkeblad. Et Ugeskrift for Kirke og Kristendom',
        'Namdalens Folkeblad',
        'Trøndelagens Blad',
        'Sarpsborg Dagblad',
        'Ugeblad for Skien og Omegn',
        'Folkehøyskolebladet',
        'Haugaland Arbeiderblad',
        'Aust Agder Blad',
        'Politik. Blad-Innlegg fraa 1870-Aari til Riksretten',
        'Samfundsbladet. Literær Skatkiste',
        'Paa gamle Tomter. Blade af Barndommens Bog',
        'Sydsvenska Dagbladet Snällposten',
        'Gymnasiastbladet',
        'Lagsblad. Bondeungdomslaget',
        'Rogalands Folkeblad',
        'Christiania Nyheds- og Avertissements-Blad',
        'Horten Dagblad',
        'Dannebrog. Ugeblad for Den danske Forening',
        'Nordlands nyt. Nyhets- og avertissementsblad',
        'Nordland Arbeiderblad',
        'Hamar Dagblad',
        'Agder Folkeblad',
        'Buskerud Dagblad',
        'Ungdomsbladet',
        'Molde Blad. Et Nyheds- og Avertissements-Blad for Romsdals Amt',
        'For Hjem og Samfund. Socialt kristelig kvindeblad',
        'Stjørdalens Blad',
        'Østerdal Arbeiderblad',
        'Samfunds-Blade',
        'Nynorsk Vikeblad',
        'Søndre Bergenhus Kirkeblad',
        'Joletre / Norsk barneblad',
        'Romsdal Folkeblad',
        'J.S. Welhaven. Mindeblade',
        'Romerikes Blad',
        'Oppland Arbeiderblad',
        'Følgeblad. Budbæreren',
        'Norsk Skoleblad',
        'Verdens Gang',
        'Politiken',
        'Fremtiden',
        'Vestlandsposten',
        'Varden',
    ];

    public static $journals = [
        'Samtiden',
        'Syn og Segn',
        'Kringsjaa',
        'Nylænde',
        'Nordisk Tidskrift',
        'Ny svensk Tidskrift',
        'Finsk Tidskrift',
        'Framtiden. Tidskrift för fosterländsk odling',
        'Framåt. Tidskrift',
        'Nordisk tidskrift för politik, ekonomi och litteratur',
        'Teologisk Tidskrift',
        'Nordisk Tidskrift for Literatur og Kunst',
        'Svensk Tidskrift',
        'Nyare bidrag till kännedom om de svenska landsmålen ock svenskt folklif. Tidskrift, Bihang',
        'Nyt Tidsskrift',
        'Norsk Tidsskrift for Videnskab og Litteratur',
        'Nyt norsk Tidsskrift',
        'Norsk Tidsskrift for Literatur',
        'Norsk Tidsskrift',
        'Theologisk Tidsskrift',
        'Historisk Tidsskrift',
        'Tidsskrift for Litteratur og Kritik',
        'Vor verden. Hvori opptatt Akademisk tidsskrift',
        'Norsk Pedagogisk Tidsskrift',
        'Vor Ungdom. Tidsskrift for Opdragelse og Undervisning',
        'For Ide og Virkelighed. Et Tidsskrift',
        'Literatur og Kritik. Et Tidsskrift',
        'Literairt Tidsskrift',
        'Teologisk Tidsskrift',
        'Pedagogisk Tidsskrift',
        'Personalhistorisk tidsskrift / Samfundet for Dansk Genealogi og Personalhistorie',
        'Kalhows Theologisk Tidsskrift',
        'Kamp og kultur. Socialistisk tidsskrift for litteratur- og samfundskritikk',
        'Nationaløkonomisk tidsskrift',
        'Tidsskrift for Skjønliteratur',
        'Ung Noreg. Litterært tidsskrift for ungdomen',
        'Kalkars Theologisk Tidsskrift',
        'Kirkeligt Folkeblad. Tidsskrift til kristelig Oplysnings Fremme',
        'Vinduet',
        'Ny Tid',
    ];

    static protected $unclassified = [
        'Mot Dag',
        'Unglyden',
        'Stavangeren',
        'Urd',
        'Norig',
        'For Kirke og Kultur',
        'Fædrelandsvennen',
        'Skilling-Magazin',
        'Throndhjems Adressecontors Efterretninger',
        'Firda',
        '1ste Mai',
        'Agderposten',
        'Nordlandsposten',
        'Sunnmørsposten',
        'Agder Tidend',
        'Norsk Tidend',
        'Statsborgeren',
        'Dovre',
        'Sarpen',
        'Hordaland',
        'Krydseren',
        'Rogaland',
        'St. Olav',
        'Gudbrandsdølen',
        'Vidar',
        'Folkevennen',
        'Teledølen',
        'Luthersk Ugeskrift',
        'Bergens Adr',
        'Den norske Folkeskole',
        'Dølen',
        'Inntrøndelagen',
        'Laagen',
        'Austland',
        'Hardanger',
        'Ung-Norig. Maanadskrift paa norsk maal',
        'Den norske Tilskuer',
        'Romsdals Budstikke',
        'Indtrøndelagen',
        'For Bygd og By',
        'Agder',
        'Hjemmet',
        'Jarlsberg',
        'Storthings-Forhandlinger',
        'Østlændingen',
        'Romsdalsposten',
        'Norske Digtere',
        'Klassekampen',
        'Nordlys',
        'Edda',
        'Norsk Ungdom',
        'Midnatssol',
        'Tilskueren',
        'Tromsø-posten',
        'Glommen',
        'Vestfold',
        'Mjølner',
        'Fjeld-Ljom',
        'Vestlandet',
        'Indlands-posten',
        'Valdres',
        'Ord & bild. Nordisk kulturtidskrift',
        'Norden',
        'Namdalen',
        'Tromsø',
        'Nora',
        'Nordisk Maanedskrift for folkelig og kristelig Oplysning',
        'Kvinden og Samfundet',
        'Demokraten',
        'For frisindet Christendom',
        'Fredriksstad Tilskuer',
        'Vor Tid',
        'Bien',
        'Fjell-Ljom',
        'Budstikken',
        'Norges Kvinder',
        'Vårt Land',
        'Tiden',
        'Rygja Tidend',
        'Nordtrønderen',
        'Dansk Maanedsskrift',
        'Vort litterære liv',
        'Sørlandets Social-Demokrat',
        'Vestmar',
        'Posten',
        'Illustreret norsk literaturhistorie',
        'Fram',
        'Bud til Menigmand',
        'Agora',
        'Nord-Trøndelag',
        'Magne',
        'Nordisk Conversations-Lexicon. Indeholdende en almindelig Forklaring over alle vigtige Navne, Gjenstande og Begreber, som forekomme i Livet under Læsning',
        'Lillehammer Tilskuer',
        'Lindesnes',
        'Ukens Revy',
        'Fremover',
        'Moss Tilskuer',
        'Østlands-posten',
        'Portræter af mærkelige Nordmænd. Med korte Levnetsbeskrivelser',
        'Grenmar',
        'Bergens Adressecontoirs Efterretninger',
        'Sørlandet',
        'Østlendingen',
        'Dag',
        'Husmoderen',
        'Otte Forfattere',
        'Kristianiaposten',
        'Fremskridt',
        'Sør-Trøndelag',
        'Spegjelen',
        'Nordlyset',
        'Menneskevennen',
        'Granskeren',
        'Arbeider-Politikken',
        'Det tyvende Aarhundrede',
        'Tids-Tavler',
        'Samhold',
        'Svein Urædd',
        'Dagbok 1905-1923',
        'Bonden',
        'Idun',
        'Friheten',
        'Fredrikshalds Tilskuer',
        'Tunsbergeren',
        'Nordmannen',
        'Norsk Maanedsskrift for Literatur, Kunst og Politik',
        'Arbeidets Rett',
        'Ny Illustrerad Tidning',
        'Clarté',
        'Tidens Krav',
        'Kiøbenhavnske lærde Efterretninger',
        'Christiansandsposten',
        'Symra',
        'Omrids af den norske Poesis Historie. literærhistoriske Forelæsninger',
        'Bogvennen',
        'Dagningen',
        'For Hjemmet',
        'Bok og Bibliotek',
        'Østlandet',
        'Nybrott',
        'Upartisk Betragtning af vor Litteratur',
        'For Folkeoplysning',
        'Velgeren',
        'Tidskrift för Hemmet. Tillegnat Nordens qvinnor',
        'Arbeideren',
        'Dagens næringsliv',
        'Smaalenenes Social-Demokrat',
        'Dagens Nyheder',
        'Hvepsen',
        'Impressionisten',
        'Karmøy-posten',
        'Nord og Syd',
        'Folket',
        'Olsok',
        'Møre Tidend',
        'Nordmands-Forbundet',
        'Forposten',
        'Lister',
        'Norske Folkeskrifter',
        'Ungdom',
        'Minerva',
        'Tyrihans',
        'Arkiv for nordisk Filologi',
        'Unge Skud',
        'Sogns Tidend',
        'Andhrimner',
        'Frifanten',
        'Kjøbenhavnsposten',
        'Oplandet',
        'Sæbyggjen',
        'Bratsberg-Demokraten',
        'Norsk Haandlexikon for almennyttige Kundskaber',
        'Horda Tidend',
        'Afhandlinger til Literaturhistorien',
        'Skiensposten',
        'Ringeren',
        'Forum',
        'Fjordaposten',
        'Straumdrag. Literære utgreidingar fraa aatti- og nitti-aari',
        'Oslo Illustrerte',
        'Forsøg i Critik og Æsthetik',
        'Göteborgs handels- och sjöfarts-tidning',
        'Norsk Salmehistorie',
        'Framgang',
        'Ny Jord',
        'Haalogaland',
        'Den Frimodige',
        'Fra Bøgernes Verden',
        'Hadeland',
        'Retfærdig Bedømmelse af Henrik Wergelands Poesi og Karakteer. En æsthetisk-polemisk Afhandling foranlediget ved J.S. Welhavens uefterrettelige Kritik i Skriftet "H. Wergelands Digtekunst og Polemik"',
        'John Klæbo. Digte og Fortællinger samt A.O. Vinjes Livshistorie',
        'Familie-Museum',
        'Ny Hermoder. Et esthetisk Ugeskrift',
        'Den norske Literatur fra 1814 til vore Dage. Et Bidrag til en norsk Literaturhistorie',
        'Vestmannen',
        'Norsk Årbok',
        'Norge',
        'Nordisk Universitets-Tidskrift',
        'Betegner den moderne Naturalisme i Poesien et Fremskridt eller et Forfald?',
        'For Folkeopplysning',
        'La Norvège littéraire. Catalogue systématique et raisonné de tous les ouvrages de quelque valeur imprimés en Norvège ou composés par des auteurs norvégiens au 19e siècle. Accompagné de renvois, notes et explications littéraires, ainsi que de notices biographiques sur les auteurs etc.',
        'Svensk Literatur-tidskrift',
        'Almindeligt norsk Maanedsskrift',
        'Det Nittende Aarhundrede. Maanedsskrift for Literatur og Kritik',
        'Svundne Tider',
        'Den nordenfjeldske Journal af Blandet Indhold',
        'Akershusposten',
        'Gjengangeren',
        'Kirke og Kultur',
        'Flekkefjordsposten',
        'Møre',
        'Den nye Social-Demokraten',
        'Det 20de Aarhundrede',
        'Norges Dæmring. En litteraturhistorisk Indledning',
        'Østerdølen',
        'BLM. Bonniers litterära magasin',
        'Fritt Ord',
        'Norsk og dansk literaturhistorie for skolen og hjemmet. Med et tillæg om de forskjellige literaturarter',
        'Nya Dagligt Allehanda',
        'Dags-Telegrafen',
        'Norges Fremtid',
        'Dagens Nyt',
        'Nordlands Framtid',
        'Hver 8. Dag',
        'Stavanger',
        'Fra det nationale gjennembruds tid. Breve fra Jørgen Moe til P.Chr. Asbjørnsen og andre',
        'Kritiske Bidrag til nyere dansk Tænkemådes og Dannelses Historie. Til biografisk Eftermæle samlede og på ny udgivne',
        'Mindedigte. Over norske og danske mænd og kvinder fra 1834 til 1877',
        'Norden har ordet. Eit stridsskrift',
        'Nordische Telegraph',
        'Akershus',
        'Tidssignaler',
        'Heimdal',
        'Figaro',
        'Janus',
        'Folketanken',
        'Bergens adressecontoirs efterretninger',
        'Nordisk Maanedskrift for folkelig og kristen Oplysning',
        'Henrik Wergeland og hans Samtid',
        'Samlede Skrifter',
        'Das Magazin für die Literatur des In- und Auslandes',
        'Heimhug',
        'Fem essays om moderne norsk literatur. Sigrid Undset, Olav Duun, Johan Bojer, Lyrik og livsfølelse, Nini Roll Anker',
        'Breve',
        'Sifuliner til Studenten Jahn Welhaven, med øvrige opbragte Compagnie af poetiske og æsthetiske Bagateller',
        'Norske Digtere. En Anthologi med Biografier og Portrætter af norske Digtere fra Petter Dass til vore Dage',
        'Kristiansundsposten',
        'For By og Bygd',
        'Sunnhordland',
        'Nordiske Kunstnere',
        'Arbeidsmanden',
        'Dagny',
        'Folkets Røst',
        'Vestopland',
        'Noreg',
        'Nor',
        'Henr. Wergelands Digtekunst og Polemik',
        'Henrik Wergeland. Afhandlinger og brudstykker efter forfatterens efterladte papirer',
        'Norske Digtere efter 1814',
        'Tidskrift for Philologi og Pædagogik',
        'Lauvsprett',
        'The Scholastic World',
        'Henrik Wergelands Skrifter i Udvalg',
        'Heimkjær',
        'Læsebog for Folkeskolen',
        'Telen',
        'Dybwads illustrerede Folkekalender',
        'Nordmanden',
        'Surnadølen',
        'Fraa By og Bygd',
        'Norsk Bog-Fortegnelse 1848-1865',
        'Karmsundsposten',
        'Avholds-arbeideren',
        'Illustrerad Tidning',
        'Illustreret Verdens-Litteraturhistorie. Under medvirkning af en kres af fag- og videnskabsmænd',
        'Ibsen og Bjørnson paa scenen',
        'Norsk Bog-Fortegnelse',
        'Wergeland og Welhaven',
        'Historisk Månedsskrift for folkelig og kirkelig Oplysning',
        'Hallo-Hallo',
        'Bore',
        'Haugesunderen',
        'Bjørnson og Ibsen i deres to seneste Værker',
        'Frie Ord',
        'Bymisjonæren',
        'Juleblus. Julebog ved Knud Clausen',
        'Kritik og Antikritik, eller Anmeldelser og Bedømmelser afde nyeste indenlandske Skrifter',
        'Sange afsungne ved det af Jøderne opreiste den 17de Juni 1849 afslørede Monument for Henrik Wergeland',
        'Register til Norsk Bog-Fortegnelse for 1848-1865, udgivetaf P. Botten-Hansen, Siegwart Petersen [og] for 1866-1872, udgivet af Thorvald Boeck',
        'Tillæg til "Forsvar for det norske Folk og Kritik over Norges Dæmring", eller Svar paa "Motiveret Protest imod Forsvaret for det Norske Folk"',
        'Hallingdølen',
        'Telemark',
        'Maanedsskrift for Litteratur',
        'Det tyvende århundrede',
        'Arne Garborg. En livsskildring. Med billeder og breve',
        'Kometen',
        'Fri Presse',
        'Nicolai Wergeland',
        'Om den norrøne litteraturs Forhold til Norge og norsk Kultur',
        'Henrik Ibsen',
        'Information',
        'Digte og Sange',
        'Udvalg af norske Digtere og Forfattere med biografiske Skisser',
        'Til Johan Falkberget på 60-årsdagen',
        'Noveller',
        'Vælgeren',
        'Nordmænd i det 19. Aarhundrede',
        'Vossingen',
        'Kritiker og Portraiter',
        'Den borgerlige Arbeider',
        'Ivar Aasen. Granskaren, maalreisaren, diktaren. Ei minneskrift um livsverket hans',
        'Camilla Colletts skrifter',
        'Norsk Folke-Kalender for…',
        'Hassel-Nødder',
        'Norge i det nittende aarhundrede. Tekst og billeder af norske forfattere og kunstnere',
        'Den høiere Skole. Meddelelser',
        'Under Dusken',
        'Revyen',
        'Indherred',
        'Literaturhistoriske Pennetegninger',
        'Det nye Nord',
        'Folkets Ven',
        'Norske Kvinder i det 19de Aarhundrede',
        'Fritt Folk',
        'Akers-Posten',
        'Nordisk Digtning. Studier og kritikker',
        'Atlantis',
        'Digte',
        'Vikingen',
        'Norske Læsefrugter. Et æsthetisk Maanedsskrift, indeholdende originale Noveller, Digte, samt Oversættelser fra den franske, engelske og tydske Literatur',
        'Dansk biografisk Lexikon. Tillige omfattende Norge for Tidsrummet 1537-1814',
        'Samliv med Ibsen, 2. samling, Sommeren i Berchtesgaden',
        'Lofotposten',
        'Fridom',
        'Dansk-norske digterværker',
        'Kritik og Polemik. Smaaskrifter',
        'Nordlands Social-Demokrat',
        'Landmandsposten',
        'Arbeiderungdommen',
        'Om de nye Psalmebøger. Aftryk af nogle Artikler (af en Theolog) i Correspondenten',
        'Stille Stunder',
        'Vort Land',
        'Om den gamle norrøne Literatur. Et Indlæg i Striden mellem Docent Grundtvig og den norske historiske Skole',
        'Beretning om Sekularfesten i Christiania den 24. juni 1840 i Anledning af Bogtrykkerkunstens Opfindelse',
        '08.05.2009',
        'Den norske Poesis Historie',
        'Udvalgte Skrifter af H. Schulze. Udgivne efter Forfatterens Død',
        'Dagen og veien',
        'The Athenæum',
        'Hanna Winsnes. En Livsskizze',
        'Bjørnstjerne Bjørnson',
        'Vår Skole',
        'Hallo! Hallo!',
        'Henrik Wergeland',
        'Kongsberg Adresse',
        'Norges første nationale Scene (Bergen 1850-1863). Et Bidrag til den norske dramatiske Kunsts Historie',
        'Den frisindede Studenterforenings foredrag og Diskussioner',
        'Vestlandsnytt',
        'Forhandlinger i Videnskabsselskabet i Christiania',
        'Illustreret Romanbibliothek',
        'Nynorsk Bokliste',
        'Finnmarken',
        'J.S. Welhaven. Liv og Skrifter',
        'Astra',
        'Sverre',
        'Eidsvold',
        'Magazin for Politik, Historie og Literatur',
        'Fred',
        'Hans Jægers sidste ord i Bohêmesagen eller, Den tale, som ikke blev holdt i Højesteret',
        'Tunsberg',
        'Sogn og Fjordane',
        'Samfundsliv',
        'Nordmør',
        'Hvad vi vil',
        'Aulestadbreve til Bergliot Ibsen',
        'Kristiania politis historie 1624-1884',
        'Henrik Wergeland. En literærhistorisk Skitse',
        'Sogn',
        'Dansk og norsk Poesis Hist',
        'Johan Nordahl Bruns Biographie',
        'Lofoten',
        'Det nittende aarhundredes Kulturkamp i Norge',
        'Samlede Noveller',
        'Livets cirkel. Bidrag til analyse av Knut Hamsuns diktning',
        'Kortfattet Omrids af den tyske Litteraturs Historie. Nærmest til Skolebrug',
        'Europear og jærbu. I serien: Arne Garborg',
        'Fielding og Smollet',
        '(Maanedskriftet) Københavns Skilderie',
        'Fra Karl Johan-Tiden',
        'Kvinner og Klær',
        'Trøndelag Socialdemokrat',
        'Konst og Æsthetik. Historiske og kritiske Bidrag',
        'Bjørnstjerne Bjørnson. Hans barndom og ungdom',
        'Kritiske Studier og Udkast',
        'Oversigt over Literaturhistorien siden Reformationen',
        'Møringen',
        'Østlandsposten',
        'Garborgs Jesus Messias. Et Indlæg',
        'Forsvarsord… i Psalmebogstriden',
        'Basar',
        'A.O. Vinje',
        'Forsøg til en Rhetorik i et Udtog af Hugo Blairs Forelæsninger over Rhetoriken. Med Hensyn til Underviisningen i de lærde Skoler',
        'Ivar Aasen. En Levnetsskildring',
        'Tone. Mauritz C. Hansens sidste Novelle. Med et Indledningsdigt af Henr. Wergeland',
        'Essays. Fremmede personligheder',
        'Henrik Wergeland. Ei folkeskrift',
        'Socialdemokratiets Aarhundrede. Fremstillinger af Arbejderbevægelsens Historie fra Revolutionen 1789 indtil vore Dage',
        'Sygna',
        'Den gamle Gaard. Barndomsminder fra Maltheby i Femtiaarene',
        'ABC',
        'Indherreds-posten',
        'Dannora. For Critik og Anticritik',
        'Nyeste Morgenpost',
        'Gita Govinda. Jayadevae poetae Indici drama lyricum',
        'Bragi',
        'Samling af Sange, Folkeviser og Stev i norske Almuedialekter',
        'Frå jærbu til europear. I serien: Arne Garborg',
        'Den ny-norske Sprog- og Nationalitetsbevægelse. Et Forsøg paa en omfattende Redegjørelse, formet som polemiske Sendebreve til Modstræverne',
        'Adolph Tidemand. Hans Liv og hans Værker. Et Bidrag til den norske KunstsHistorie',
        'Erindringer fra mine unge Dage',
        'Sagn fra Telemarken',
        'Historiske Samlinger',
        'Lys over Land',
        'Gads danske Magasin',
        'Den 1 7de Mai',
        'Ord for dagen',
        'Vi kvinder og vore digtere',
        'Fra Nordens natur og folkeliv. Poesi og prosa i udvalg af forskjellige forfatteres skrifter',
        'Fædrelandet og Emigranten',
        'Minder fra Bergens første Nationale Scene',
        'Oplysning om de Salmers Oprindelse og Forfattere, som ere optagne i den ny, autoriserede Kirkesalmebog, samt om deres Forekomst i ældre dansk-norske Kirkesalmebøger',
        'Bidrag til den oldnordiske Literaturs Historie',
        'Aftenlæsning',
        'Nord-Norge',
        'Gamle skaldar og kvad. Med kvadi umsette paa nynorsk',
        'Den yngre akademiske Slægt. Studier og Betragtninger',
        'M. Goldschmidts Norden',
        'Den nye Tid',
        'Kvindeskikkelser i norsk aandslivs historie. Alvilde Prydz',
        'Posthornet. Magasin for medlemmer i Norsk post- og kommunikasjonsforbund',
        'Camilla Colletts Livs Historie. Belyst ved hendes Breve og Dagbøker',
        'Hamar-ringen',
        'Oslo',
        'Något om Hans Jægers bok "Fra Christiania bohemen" samt ett inlægg i frågan om æktenskapet och den fria kærleken',
        'Om modsætningen mellem det vestlige og østlige Norge. Ved tusindaarsfesten til minde om Norges samling som rige',
        'Ny Dag',
        'Wergeland som Digter',
        'Enkelte af Ole Vigs Arbeider til Folkelæsning',
        'Saamanden. Et religiøst Maanedsskrift',
        'Foredrag over B.B.s drama Over ævne',
        'Minde ved Henrik Wergelands Grav',
        'En Anmeldelse af "Amtmandens Døttre"',
        'Ryfylke',
        'Arbeider-Magasinet',
        'Bjørnstjerne Bjørnson. Høvdingen. 8. december 1910 in memoriam',
        'Norske Forfattere. Literaturbilleder',
        'Norsk Litteraturhistorie',
        'Efterladte skrifter I',
        'Paa skuggesida. Forteljingar',
        'Indledning i Norges og Danmarks Literatur',
        'Fortsatte, frimodige Bemærkninger over Sølvværket Kongsberg. Med Svar til den unævnte Anmelder af mit Skrift. Kongsberg eller Norges Sølvværk. Første Bilag',
        'Andvake',
        'Minder fra Bjørnson-tiden 1874-1909. Rom, Aulestad, Larvik',
        'I Anledning af O. Skavlans Skrift om Henr. Wergeland',
        'Hålogaland',
        'Norge og Nordmændene. Reiseerindringer fra 1836 og 1865',
        'Norsk Litterær Årbok',
        'Kunst, kamp, kultur. Gjennem 40 aar i tekst og billeder. Originaltegninger og skisser fra kunstnerens egne samlinger',
        'A.O. Vinjes skrifter i Utval',
        'Nya Argus',
        'Opdalingen',
        'Vest-Agder',
        'Norsk Forfatter-Lexikon 1814-1856',
        'Peter Christen Asbjørnsen. En literær-biografisk Skitse',
        'Læsebog i Modersmaalet for Skolernes højere Klasser. Tilligemed svenske Læsestykker og en litterærhistorisk Oversigt',
        'En lumsk Avindsmand trukken frem og skildret efter Naturen i Anden Række Sifuliner til en Student Jahn Welhaven',
        'Afhandlinger og Kritiker',
        'Har Henrik Ibsen i Hedda Gabler skildret virkelige Kvinder?',
        'Gøsta af Geijerstam. Et førfattarportrætt',
        'Nogle aandelige Sange',
        'Bergens Kunstforening i femti Aar',
        'Fra Udlandet',
        'For Romantik og Historie',
        'Tidsnornerne, et Leilighedsdigt',
        'Henrik Ibsen og hans Værker. En Fremstilling i Grundrids',
        'Norsk realisme i 1830 og 40 aarene. Et bidrag til Intelligenspartiets historie',
        'Godtemplar-Ungdommen',
        'Holbergs minde helliget, da comedien Den politiske kandestøber ..., blev givet paa det Dramatiske selskabs theater i Bergen 11/1 1822',
        'Norsk Illustreret Kalender',
        'Norske Viser og Stev',
        'Skogbrukeren. Organ for skognæringen',
        'Meninger om bøker og forfattere',
        'Om den saakaldte litterære og kunstneriske Eiendomsret',
        'Om troper og figurer. Med en indledning om fordringerne til den gode stil i almindelighed, nærmest for middelskolen',
        'Om de Hamarske Krøniker',
        'Johan Nordahl Brun. En monografi',
        'Norsk Familie-Journal',
        'Natur, Folkeliv og Folketro i Hardanger. Belyst ved Natur- og Folkelivsskildringer, Eventyr, Sagn,Fortællinger osv. fra ældre og nyere tid',
        'Om Ludvig Holberg',
        'Skandinaven',
        'Alexander L. Kielland og hans samtid',
        'Julehelg. Forfatterforeningens julehefte',
        'Notitser af den norske og danske Literaturhistorie',
        'Unge Agder',
        'Den norske Forfatningskamp',
        'Martin Luthers aandelige Sange',
        'Kristiania-bohemen på äfventyr. En promenad på Karljohansgatan och dess följder. Första aftonen',
        'Minde ved Henrik Wergelands grav',
        'Schiwes Nyeste Skilderi',
        'Kvinnen og Tiden',
        'Schleswig-Holstein-Lauenburgischen Kirchen- und Schulblattes',
        'Stemninger',
        'Norges gymnasiaster. Sammenslutning av "Gymnasiasten" og "De Unges Forbund"',
        'Hesperus. For fædrenelandet og litteraturen',
        'Norges politiske Historie 1815-1885',
        'Ludvig Holbergs unge dage. Med forskjellige bidrag til det historiske tidsbillede',
        'Kunstrevyen. Organ for norske kunstnere',
        'Ugebl for Den Danske Folkekirke',
        'Berlingske Tid',
        'Chr. Monsens Samlede Digte',
        'Literært Album. Med Bidrag af norske Forfattere',
        'Glåmdalen',
        'For By og Bygd. Literært Maanedsskrift',
        'Historisk Udsigt over Bogtrykkerkonsten fra dens Begyndelse til nærværende Tid. Et Indbydelsesskrift til Sekularfesten i Christiania d. 24 Juni 1840',
        'København',
        'Oplandsposten',
        'Fra tid til anden. Bøker og digtere',
        'Ungviljen',
        'Wäktaren',
        'Norstedts Nyheter',
        'P.A. Munchs Levnet og Breve i Familiekredsen',
        'Oplysningskontorets studieplaner',
        'Skaldemaal',
        'Tvedestrandsposten',
        'Peter Andreas Munch',
        'Politisk digtning i Norge i 1814',
        'Herdafylket',
        'Mennesket i øieblikket',
        'Om Peder Claussøn Friis og hans skrifter. Indledning til den norske historiske Forenings Udgave af hans Skrifter',
        'Biografiske Efterretninger m.m. vedkommende Studenterne fra Aaret 1831 (i Anledning af deres Femtiaarsjubilæum i 1881)',
        'Henrik Wergeland og Norge i hans Dage',
        'Romsdalingen',
        'Udvalgte Digte',
        'Defensions-skrift...',
        'Hemmet och Samhållet',
        'Digte og Fortællinger, ældre og nyere',
        'Biographisk skitse. Indledning til "Mit levnet"',
        'Bergens  adressecontoirs  efterretninger',
        'Henrik Wergeland i hans digtning',
        'Kjenn ditt land / Norgeshefter',
        'Erika',
        'Jubilæumsboken. Fra 14 til 14',
        'Kort Udsigt over den franske National-Literaturs Historie indtil Revolutionen',
        'Books Abroad',
        'Hardanger Social-Demokrat',
        'Knut Hamsun',
        'Religiøse Digte',
        'Biografiske Efterretninger om de 830 elever, der har gaaet paa Fredrikshalds Latin- og Realskole i 50 Aar fra dens Begyndelse 1823 til 1872',
        'Om Udviklingsgangen i Henrik Ibsens Digtning',
        'Norge. Norsk Kalender',
        'Hjemmets og Arbeiderens Ven',
        'Bjørnstjerne Bjørnsons Liv og Forfattervirksomhed. Aktmæssig fremstillet',
        'Morgendæmring. En Samling Fortællinger og Digte af unge norske Forfattere',
        'Den Fornøielige Tugtemester. Kritik over H. Wergelands nyeste Digt. Den engelske Lods',
        'Jonas Lie. En Udviklingshistorie',
        'Blätter für Literarische Unterhaltung',
        'Norsk Anthologie',
        'Literære Nyheder',
        'Attersyn',
        'Christiania Videnskabs-selskabs Forhandlinger',
        'Udsigt over den romerske Satires forskjellige Arter og deres Oprindelse',
        'Trøndelagen',
        'Læredigtet i Nordens poetiske Literatur',
        'Stavanger Social-Demokrat',
        'Cohlmanns Nordisk Tidsskr',
        'Brands døtre. Et Livsbillede',
        'Lesebok for folkeskulen',
        'Henrik Ibsen. Festskrift i anledning af hans 70de fødselsdag',
        'Claus Fasting. Til Bergens Historie',
        'Dag og Tid',
        'Af den tyske Literaturhistorie',
        'Land og Folk',
        'Blinken',
        'Norges Literatur 1814-1870',
        'Tidskrift Landsmålsföreningen',
        'Vagant',
        'Stockholms-Tidningen',
        'Familie-Erindringer. 1831-1856',
        'Idunna',
        'Studier over Schelling. Afhandling for den philosophiske Doctorgrad',
        'ABC. Om Ringen sluttet',
        'Olaves Pedersens Viser',
        'Universitets- og Skole-Annaler',
        'Ludvig Holberg',
        'Mennesker og makter. Sigrid Undsets middelalderromaner',
        'Critica',
        'Fra Bjørnsons sidste Aar. Erindringer fra Aulestad og Paris',
        'Fagnafolk. Dikt',
        'Nordlands Trompet',
        'Norsk Tidsskr',
        'Litteraturen. Nordens kritiske revue',
        'Meiningar um Jesus',
        'Ragnhild Jølsen i liv og digtning. Med bruk av utrykte manuskripter',
        'Arne Garborg. Ein Fyretalsmann',
        'Erindringer fra Henrik Ibsens Ungdomsaar',
        'Barndomshjemmet',
        'Oversættelse med Anmærkninger af det Interessanteste af "Excursions in New South-Wales, Western Australia and Van Diemens Land during the Years 1830,31,32,33". Med Fortegnelse over hvad Oversætteren har ladet trykke, og hans Selv-Biographie',
        'Fylkingen',
        'Ruskkaja Mysl',
        'Ibsens diktning og Ibsen selv',
        'Henrik Ibsen. 1828-1888. Et literært livsbillede',
        'Storbonden og hans Sønner. En Fortælling fra Schwarzwald. Tillægshefte til Folkevennen',
        'Prolog fremsagt paa Bergens Privattheater ved Skuespillene, som gaves til Bedste for de meest trængende Brandlidte 1830',
        'Fremtidens Muligheder, eller "Over Evne". Anden Fredsbog. Om Fremskridt og Tilbagegang. Et Blik paa vor Literatur',
        'Mennesker',
        'Udførlig beretning om Henrik Wergelands mindefest, feiret i Stockholm den 22de october 1847',
        'Frisprog',
        'Bokanmelderen',
        'Henrik Wergelands Samlede Skrifter',
        'Dagens Nyheter',
        'Træk af Henrik Wergelands Liv og nogle af hans Digte',
        'Et par Ord om Norges Dæmring og Welhavens polemiske Digtekunst',
        'Paa Veien hjem. Nogle aandelige Sange samt en kristelig Betragtning. Udgivne efter Opfordring fra den Afdødes Venner og med hans Biografi',
        'Gildet paa Solhoug',
        'Sigurd Christiansen i liv og diktning',
        'Bibliogr. Samlinger til d. æ. da.-no. litt.hist.',
        'Magdalene Thoresen',
        'Norske Digteres Vilkaar',
        'Skiensfamilien Flood og dens legatberettigede Descendenter af familierne Bull, Christi, Clason, Colbjørnsen, Engelhart, Hald, Hansen, Helsing, Mathiesen, Mortensen, Petersen, Rønning, Schancke, Thomesen, Wamberg, Vetlesen, Wessel',
        'Holberg som Komedieforfatter. Forbilleder og Eftervirkninger',
        'Af Dagens Krønike. Maanedskrift for Literatur, Kunst og Politik',
        'Litterær Polemik',
        '08.05.2011',
        'Nybrot',
        'Hver 8. dag',
        'Aarbøger for nordisk oldkyndighed og historie',
        'Georg Brandes 1842-1912. Fra Norge paa syttiaarsdagen',
        'Nord und Süd',
        'Bjørnstjerne Bjørnson. Hans barndom og ungdom I-II',
        'Henrik Wergeland og Stella',
        'Læsebog i Modersmaalet for Norske og Danske, tilligemed en Exempelsamling af den svenske Literatur og med æsthetiske og literaturhistoriske Oplysninger',
        'Om Ægteskabsidéen i Fruen fra Havet',
        'Breve fra Henrik Wergeland',
        'Henrik Ibsens Kvindeskikkelser',
        'Aasmund Vinje i Staale-diktet. Med lyriske dikt or "Staale"',
        'Adskilligt om og til kvinden',
        'Udvalgte Digte af Henrik Wergeland',
        'Henrik Ibsen i sin avstamning - norsk eller fremmed?',
        'Henrik Wergeland i Digt og Liv. En historisk Skitse',
        'Kritisk og antikritisk Journal for Litteraturen i de danske Stater',
        'Haandbog i Oldtidens Literaturhistorie',
        'Telemarksposten',
        'Mellemakten',
        'Festskrift til William Nygaard. I anledning av hans 25-aars jubilæum som forlagsboghandler 1888 - 20. september - 1913',
        'Norskhet i sproget hos Henrik Wergeland og hans samtid',
        'Lolland-Falsters Social-Demokrat',
        'Frankfurter Zeitung und Handelsblatt',
        'Dagens Tid',
        'Saltens Fremtid',
        'Hvorledes P.Chr. Asbjørnsen begyndte som sagnfortæller',
        'Reformjüdische Polemik gegen das Christenthum im Gewande moderner Aesthetik',
        'Vesle Kari, eller De Forældreløse. Fortælling',
        'Juleaften. Fortælling',
        'Fredrikssten',
        'Nogle Bemærkninger i Anledning Prestevisen "Til Norges Folk"',
        'Register over samtlige Vers i Landstads Salmebog',
        'Luren',
        'Sigrid Undset',
        'Den hellige Kong Haakon og Folke-Visen om hans Død',
        'Knut Hamsun. En studie',
        'Henrik Wergeland. Hans Liv og Virken; Læsning for Folket',
        'Fra det mørke Fastland. Reiseindtryk fra Stavanger og Jæderen',
        'Theatervennen',
        'Arena',
        'Nordmenn i Amerika',
        'Fragmentariske Studier over A. Munchs Tragødie. Lord William Russell',
        'Fuglene',
        'Nissen. Riimbrev til Henrik Ibsen',
        'Om Henrik Ibsen. Fruen fra Havet og Personerne deri',
        'Det store Vendepunkt i Holbergs Liv',
        'Emigranten',
        'Forfatterlexikon',
        'Krig og Fred',
        'Tale ved Henrik Wergelands grav',
        'Sportsmanden',
        'Bergenseren',
        'Kritikken',
        'Det gamle Christiania. (1624-1814)',
        'Henrik Ibsen og Christiania Theater 1850-1899. Et Bidrag til den Ibsenske Digtnings Scenehistorie',
        'Nordisk Tidskr for Literatur og Kunst',
        'Vår tid',
        'Striden om norske forfattere og danske forlæggere',
        'Løvsprætt. Fortælling',
        'Indførelse i kirkelige Salmer efter Landstads Salmebog',
        'Vaar fedra-arv. Foredrag ved folkemøtet paa Mælen den 6te januar 1880',
        'Barndoms- og Ungdomsminder om Henrik Wergeland',
        'Patrioten',
        'Solen i Tomtegaden eller Digterklubben',
        'Athenæum',
        'Storthingsrepræsentanter og Suppleanter. 1814-1891. Biografisk og kronologisk Fortegnelse',
        'En Dag i det Frie. En Historie for Hvermand i Anledning af en saakaldet Vaudeville med samme Navn opført paa det offentlige Theater i Bergen den 3die Mai d.a.',
        'Disse fjerne år. Tids- og miljøskildringer fra Norge i tiden omkring århundreskiftet og frem til verdenskrigen',
        'Kirkehistoriske Samlinger',
        'Bjørnsoniana',
        'Holberg og England',
        'Min lille Bog. Minder og stemninger',
        'Tidskifte',
        'Kvindernes Bog. Seks Portrætter. Autoriseret Oversættelse',
        'Gøteborgs Morgonpost',
        'Det norske målstrævs historie',
        'Kooperatøren',
        'Tro og detailleret fremstilling af det berømte theaterslag i Christiania den 28de Januar 1838',
        'Om Schweigaard',
        'Endnu et par ord om fru Colletts "Fra de stummes lejr"',
        'Studenterne fra 1851',
        'Bok og bibliotek',
        'Poetisk Læsebog for Børn og barnlige Sjæle, til Brug saavel i Skolen som i Huset',
        'Bjørnstjerne Bjørnsons breve til Alexander L. Kielland',
        'Studier og portræter',
        'The School for Scandal. A Comedy',
        'Arbetet',
        'En Mislyd',
        'Trondhjem Adressecontors Efterretninger',
        'Vestfold Fremtid',
        'Forsøk til en Sigrid Undset bibliografi til hennes femtiårsdag 20de mai 1932',
        'Den Konstitutionelle. Nissespill',
        'Nationalt Selvmord. Et Foredrag',
        'Samlede Digte',
        'Efterretninger om lærde Sager',
        'Mindre Fortællinger og Skisser',
        'Brev til Henrik Wergeland',
        'Fra Holberg til Hamsun. Skrevet og talt',
        'Fredrikshalds h. offentlige almueskole, årsberetning',
        'Henrik Ibsens Keiser og Galilæer. Et indledende foredrag ved en diskussion i det Norske studentersamfund',
        'Om den christelige Psalmesang. Et Sendebrev til Hr. Pastor Andr. N.H. Stenersen i Anledning af hans Opsats om Psalmesagen',
        'Bidrag til den danske literaturs historie',
        'Biskop Thomas Kingos Biografi',
        'Throndhjems Smaaskrifter 1',
        'Gjenmæle i Salmebogsstriden. Et Bidrag til retfærdig Bedømmelse af Landstads Salmebog',
        'Norway illustrated. With a short description',
        'Garborg 1851-1921',
        'Udkast...til en norsk Bogtrykker-Historie',
        'Kampen om kjærlighed og kunst i naturalismens tidsalder',
        'Anders Reitan. En Levnetsskildring',
        'Kysten',
        'Tre Dosin Complimenter til Henrik Wergeland',
        'Sosialistisk perspektiv',
        'Storegut. Ættesogo og diktverket',
        'Prometheus i Lænker. Tragedie',
        'Forsvar for det norske Folk og udførlig Kritik over det berygtede Skrift Norges Dæmring',
        'Dramatiske Forsøg',
        'Samlede Afhandlinger',
        'Storm og Stille. Kristelige Digte og Sange',
        'Hans Adolf Brorson som Salmedigter',
        'Norske Bondeblomster. Poetiske Forsøg',
        'Søndagen',
        'Undersøgelse af Kongesagaens Fremvæxt',
        'A.O. Vinje. Stutt livsskildring',
        'I de Lange Nætter',
        'Fortegnelse over de i Norge udkomne bøger i aarene 1814 til 1831',
        'Skrifter',
        'Schirers Familienblatt',
        'Intelligentsbl',
        'Tidskrift för bildande konst och konstindustri',
        'Bohemen i sidste Akt. Indlæg mod Bohemeliteraturen',
        'Finnes der Trykkefrihed i Norge?',
        'Ur dagens Krønika',
        'Mindebl fra "Societas Nidarosiensis"',
        'Familien Stillesen',
        'Retfærd',
        'Norsk Folke-Kalender eller Aarbog',
        'Wergeland - Bjørnson - Sverdrup. Folkelige Foredrag',
        'Hvorledes jeg blev profet, eller En bohêmes eventyr i Stockholm',
        'Nordland',
        'Amalie Skram som kunstner og menneske',
        'Folkelæsning',
        'Alli Tryggs Julehilsen',
        'Efter læsningen af Bygmester Solness. En samtale',
        'Sange og Leilighedsdigte',
        'Festskrift til Francis Bull på 50 årsdagen',
        'Alf Collett. En Gammel Christiania-Slægt. Optegnelser om Familien Collett og Christianias Fortid',
        'Arne Garborg. 25. januar 1851 - 25. januar 1921',
        'Norskrift',
        'Bjørnstjerne Bjørnson. Bidrag til digterens karakteristik skrevet i anledning afhans 70-aarige fødselsdag',
        'Om Dagens indre Strid',
        'Sandhedens Røst til Hr. Literatus Blok Tøxen',
        'Indbydelsesskrift (Kristiansund off. høgre almenskole)',
        'Forstadsposten',
        'Telemarks festskrift 1914',
        'En lægmand orienterer sig i tilværelsen',
        'Sang i Anledning...det dramatiske Selskab',
        'Jesus Messias. Et foredrag om Garborgs bog',
        'Theater-Anliggender. Et Stridsskrift',
        'Modern. En berättelse',
        'Anti-impressionisten',
        'Samarbeid',
        'Johan Ludvig Runeberg och Fänrik Ståls sägner. Ett bihang till Fänrik Ståls sägner',
        'Gamle Dage. Erindringer og Tidsbilleder',
        'Elverum',
        'Det Skjønne i Kristendommens Lys. Studier over Gudsbilledets Skjønhedsside i dens Forhold til det Sande og det Gode',
        'Erindringer. Sidste Samling',
        'Mine Erindringer',
        'Udvalg af Claus Fastings forhen trykte og utrykte Skrifter, med Bidrag til hans Biographie',
        'Nordisk Digtning',
        'Fri Skilsmisse. Indlæg i Diskussionen om Kjærlighed',
        'Motiveret protest imod skriftet. "Forsvar for det norske folk"',
        'Gøteborgsposten',
        'Bondestudentar',
        'Hjemmenes Vel',
        'Literaturen og dens Dele. En Indledning til Literaturstudium',
        'Henrik Ibsen - Eit diktarliv I-II',
        'Sjeleild mot elementer. Festskrift til Rolf Nyboe Nettum på 90-årsdagen 17. juni 2009',
        'Min forsvarstale i Højesteret',
        'Julerosen',
        'Illustreret Ugerevy',
        'Nordisk Tidskr',
        'Rjukan',
        'Det skönas verld. Estetik och konsthistoria med specielt afseende på den bildande konsten, populärt framställda',
        'Peder Dass',
        'Minder fra Hjembygden',
        'Ivar Aasen',
        'Gaula',
        'Hedenske og kristelige Tanker om Ægteskabet. Prædiken paa anden Søndag efter Hellig tre Konger',
        'Fris',
        'Digtninger',
        'Litterär Kritik',
        'Lauvduskar',
        'Sjøfarten',
        'Hans Nielsen Hauge og Henrik Vergeland. En Fremstilling af den religiøse og den folkelige Vækkelse i Norge',
        'Uken',
        'En norsk Borgers Stemme i Anledning af den welhavenske "Norges Dæmring" m.m.',
        'Efterladte Arbeider i Vers og Prosa',
        'Bøker og mennesker',
        'Om Petter Dass og hans Skrifter',
        'Mixed Pickles. Feuilletoner og skitser',
        'Klinte',
        'Bj. Bjørnson. Samlede digte',
        'Samfundet',
        'Norsklæreren',
        'Hartvig Lassen og Theateret og Theateret og Hartvig Lassen',
        'Haandbog i Middelalderens Literaturhistorie',
        'Kvinderne i Bjørnsons digtning. Essay',
        'Macbeth. Tragedie i fem Akter',
        'Henrik Ibsen bedømt af samtid og eftertid. Et forsøg',
        'Bærum',
        'Mod Bjørnstjerne Bjørnsons Angrep paa den Kristne Tro',
        'Polemiske Sonetter. Et Tilsvar',
        'Reichsboten',
        'Daae. Biografiske og literærhistoriske meddelelser',
        'Sange og Digte',
        'Epilog i det dramatiske Selskap',
        'Norsk Folke-Kalender eller Aarbog. Største Udgave. Med Bidrag af flere Forfattere',
        'Våre Høvdinger - Folkeutgave',
        'Nordens Aarbok',
        'To literære Studier',
        'Gøteborgs Handelstidning',
        'Norsk Ugeskrift',
        'Litterære Tendenser. Artikler og Anmeldelser',
        'Lutheraneren',
        'Rolf Stenersen og hans skuespill',
        'Et lyst Billede i en mørk Ramme',
        'Olav Duun',
        'Norsk Dame-almanak',
        'Fra Tyveaarene og lidt mere',
        'Sigbjørn Obstfelder i hans digtning og breve. En psykologisk studie',
        'Testamentet fra America. Originalt norsk Skuespil med Sang i fem Acter',
        'Camilla Collett. Et Livsbillede',
        'Samlede verker',
        'Conversations-Lexicon der neuesten Zeit und Literatur. Brockhaus',
        'Eventyr for folket',
        'Corsaren',
        'Ibsen og Bjørnson på scenen',
        'Maria Schandorff. Et Mindeskrift',
        'Europearen. I serien: Arne Garborg',
        'Norske Folkeeventyr',
        'Bjørnsonstudier',
        'En Samfunds-Idé og dens Digtere II',
        'Revy',
        'Nordmanns-Forbundet',
        'Til Gerhard Gran 9. december 1916',
        'For Almuen',
        'Arne Garborg. Svein og meister. Ei historisk-genetisk innleiding til gjenombrotsdiktinga hans',
        'Gabriel Finne i lys av sin samtid',
        'Nordische Reichspost',
        'Vor gamle bondekultur',
        'Laagendalsposten',
        'Samliv med Ibsen',
        'Theateralmanak. Nytaarsgave for 1833',
        'Dramatiske Selskab i Bergen 1794-1894. Et Festskrift i Anledning af Selskabets hundredaarige Bestaaen',
        'Johan Sebastian Welhaven',
        'Henrik Wergeland. (Etter eit Fyredrag fyre Bønder)',
        'Kort Udsigt over Ludvig Holbergs Liv og Virksomhed',
        'Samlede Værker',
        'Sogns Tid',
        'Vort Arbeide',
        'Om Bjørnstjerne Bjørnsons "Arnljot Gelline". Oversigter, historiske oplysninger og literære anmerkninger',
        'Autobiografi',
        'Kristus eller Ibsen?',
        'Akademisk Revy',
        'Nordisk familjebok. Konversationslexikon och realencyklopedie innehållande upplysningar och førklaringar om mærkværdiaga namn, føremål och begrepp',
        'Omrids af den nyere Tids Literatur (e. 1517)',
        'Kunstnere',
        'Norsk studentforum',
        'Solungen',
        'Bjørnstjerne Bjørnson og den nyere norske Poesi',
        'Salt fraa folkehøgskulen',
        'Studenter-komedier',
        'Troubadourpoesien og Troubadourerne',
        'Halden',
        'Da de var unge',
        'Teaterkatten',
        'Øvre Smaalenene',
    ];

    static public function isNewspaper($value) {
        return in_array($value, self::$newspapers, true);
    }

    static public function isJournal($value) {
        return in_array($value, self::$journals, true);
    }
}
