---
- become: yes
  tasks:

    - name: Add the 'deploy' user
      user:
        name: deploy
        comment: Deploy user for ub-baser
        shell: /bin/bash
        create_home: true

    - name: Add authorized key for user 'deploy'
      authorized_key:
        user: deploy
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.ub-baser-deploy.pub') }}"

    - name: Add Docker repository
      yum_repository:
        file: docker-ce
        name: docker-ce-stable
        description: Docker CE repo
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        gpgkey: https://download.docker.com/linux/centos/gpg
        gpgcheck: yes
        enabled: yes

    - name: Installing Packages
      yum:
        name: "{{ packages }}"
      vars:
        packages:
          - git
          - vim
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - rh-php72
          - rh-php72-php-pdo
          - rh-php72-php-pgsql
          - rh-nodejs10

    - name: Installing Docker
      yum:
        name: "{{ packages }}"
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Open ports 80 and 443
      firewalld:
        permanent: yes
        state: enabled
        zone: public
        service: "{{ item }}"
      with_items:
        - http
        - https
      notify: Reload firewall

  handlers:
    - name: Reload firewall
      systemd:
        name: firewalld
        state: reloaded

    - name: Restart firewall
      systemd:
        name: firewalld
        state: restarted
