version: '3'

volumes:
  storage:
  pgdata_dev:

services:

  db:
    build: ../postgres
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    ports:
      - 5999:5432
    container_name: ub-baser-db
    environment:
      - POSTGRES_USER=ub-baser-dev
      - POSTGRES_PASSWORD=ub-baser-dev
      - POSTGRES_INITDB_ARGS=--no-locale --encoding=UTF8

  app:
    image: ub-baser:latest
    build:
      context: ../..
      dockerfile: docker/Dockerfile
      args:
        - GITHUB_TOKEN
    environment:
      - APP_ENV=dev
      - APP_DEBUG=true
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ub-baser-dev
      - POSTGRES_USER=ub-baser-dev
      - POSTGRES_PASSWORD=ub-baser-dev
      - APP_KEY=DoesNotNeedToBeRandomInDevEnviro
      - SAUCE_USERNAME
      - SAUCE_ACCESS_KEY
      - TEST_BASE_URL=http://localhost:8080
    ports:
      - 8080:80
    volumes:
      - ../..:/app/:ro
      - storage:/app/storage
      #- ../../storage:/app/storage
    depends_on:
      - db
    container_name: ub-baser-app
