version: '3'

services:

  db:
    image: ${POSTGRES_IMAGE}
    environment:
      - POSTGRES_USER=ub-baser-staging
      - POSTGRES_PASSWORD=ub-baser-staging
      - POSTGRES_INITDB_ARGS=--no-locale --encoding=UTF8

  app:
    image: ${APP_IMAGE}
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ub-baser-staging
      - POSTGRES_USER=ub-baser-staging
      - POSTGRES_PASSWORD=ub-baser-staging
      - APP_KEY=DoesNotNeedToBeRandomInDevEnviro
    ports:
      - 8080:80
    depends_on:
      - db

  test:
    image: ${APP_IMAGE}
    command: npm run test@sauce
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ub-baser-staging
      - POSTGRES_USER=ub-baser-staging
      - POSTGRES_PASSWORD=ub-baser-staging
      - APP_KEY=DoesNotNeedToBeRandomInDevEnviro
      # Test stuff
      - TEST_BASE_URL=http://localhost:8080  # URL reachable from the sauce connect proxy, not from this container
      - SAUCE_BUILD
      - SAUCE_TUNNEL
      - SAUCE_USERNAME
      - SAUCE_ACCESS_KEY
    ports:
      - 8080:80
    depends_on:
      - db
      - app
