export { default as SimpleInput, default as UrlInput } from './SimpleInput.vue'
export { default as AutocompleteInput } from './AutocompleteInput.vue'
export { default as RangesliderInput } from './RangesliderInput.vue'
export { default as PersonsInput } from './PersonsInput.vue'
export { default as BooleanInput } from './BooleanInput.vue'
export { default as TagsInput } from './TagsInput.vue'
export { default as SelectInput } from './SelectInput.vue'
export { default as EnumInput } from './EnumInput.vue'
