name: Build, test and deploy

on:
  push:
  repository_dispatch:
  schedule:
    - cron:  '0 5 * * 6'    # Weekly
jobs:

  build-postgres:
    name: Build Postgres image with Norwegian locale
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.6.1
        with:
          push: true
          context: ./docker/postgres
          tags: |
            ghcr.io/uio-library/postgres:12-nb_NO

  build-app:
    name: Build main Docker image
    runs-on: ubuntu-latest
    env:
      APP_ENV: staging
    steps:

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker (app)
        id: app_meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/uio-library/ub-baser
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,format=long,prefix=

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.6.1
        with:
          push: true
          file: docker/Dockerfile
          tags: ${{ steps.app_meta.outputs.tags }}
          labels: ${{ steps.app_meta.outputs.labels }}

  test:
    name: Run test suite
    runs-on: ubuntu-latest
    needs: [build-postgres, build-app]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start Sauce Connect Proxy
        uses: saucelabs/sauce-connect-action@v1
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          tunnelIdentifier: gh-job-${{ github.run_id }}
          scVersion: 4.6.4

      - name: Run tests
        run: docker-compose run test
        env:
          COMPOSE_FILE: docker/compose/staging.yml
          APP_IMAGE: ghcr.io/uio-library/ub-baser:${{ github.sha }}
          POSTGRES_IMAGE: ghcr.io/uio-library/postgres:12-nb_NO
          GITHUB_SHA: ${{ github.sha }}
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          SAUCE_TUNNEL: gh-job-${{ github.run_id }}
          SAUCE_BUILD: ${{ github.sha }}

  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/main'
    environment: production
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Update Docker service
        uses: appleboy/ssh-action@v0.1.4
        with:
          # ub-baser uses RSA key as of 2021-09-02
          # ssh-keygen -l -f /etc/ssh/ssh_host_rsa_key.pub | cut -d ' ' -f2
          fingerprint: SHA256:FodC+d75yjynzZlCTLw6xGFmLfDJ/NUogzRSlmDK054
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          passphrase: ${{ secrets.DEPLOY_KEY_PASSPHRASE }}

          # login.uio.no uses RSA key as of 2021-09-02
          # ssh-keygen -l -f /etc/ssh/ssh_host_rsa_key.pub | cut -d ' ' -f2
          proxy_fingerprint: SHA256:j+wXLffQHfeQuqO6tUdB2520w2R9Bi9zakAB6tyHtqo
          proxy_host: ${{ secrets.DEPLOY_PROXY_HOST }}
          proxy_username: ${{ secrets.DEPLOY_PROXY_USERNAME }}
          proxy_key: ${{ secrets.DEPLOY_PROXY_KEY }}
          proxy_passphrase: ${{ secrets.DEPLOY_PROXY_KEY_PASSPHRASE }}

          script: |
            docker service update --image ghcr.io/uio-library/ub-baser:${{ github.sha }} ub-baser_app
