name: Build Docker image

on:
  push:
    branches:
      - 'main'
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_ENV: staging
    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.6.1
        with:
          push: true
          tags: scriptotek/ub-baser:latest
